#include "bsp_led.h"

// 初始化LED的GPIO
void init_led(){
	volatile uint32_t debug_ahb1enr_value = 0x00000000;
	
	REG_SET(RCC_AHB1ENR, RCC_AHB1ENR_GPIOFEN);			// 开GPIOF的时钟
	
//	// C语言规定有符号不可以左移到符号位，所以中间这句在被移数前面加了个(uint32_t)强转无符号数，或者写成0x0FU也行
//	REG_SET_VALUE((GPIOF_AFRL), (0x0F << LED_RED_GPIO_PIN * 4), (GPIOF_AF_NONE << LED_RED_GPIO_PIN * 4));
//	REG_SET_VALUE((GPIOF_AFRL), ((uint32_t)0x0F << LED_GREEN_GPIO_PIN * 4), ((uint32_t)GPIOF_AF_NONE << LED_GREEN_GPIO_PIN * 4));
//	REG_SET_VALUE((GPIOF_AFRH), (0x0F << (LED_BLUE_GPIO_PIN - 8) * 4), (GPIOF_AF_NONE << (LED_BLUE_GPIO_PIN - 8) * 4));
	
	// 配置PF6
	REG_SET_VALUE((GPIOF_MODER), (0x03 << LED_RED_GPIO_PIN * 2), (0x01 << LED_RED_GPIO_PIN * 2));
	REG_SET_VALUE((GPIOF_OTYPER), (0x01 << LED_RED_GPIO_PIN), (0x00 << LED_RED_GPIO_PIN));
	REG_SET_VALUE((GPIOF_OSPEEDR), (0x03 << LED_RED_GPIO_PIN * 2), (0x03 << LED_RED_GPIO_PIN * 2));
	REG_SET_VALUE((GPIOF_PUPDR), (0x03 << LED_RED_GPIO_PIN * 2), (0x00 << LED_RED_GPIO_PIN * 2));
	REG_SET(GPIOF_BSSR, (0x01 << (LED_RED_GPIO_PIN)));
	
	// 配置PF7
	REG_SET_VALUE((GPIOF_MODER), (0x03 << LED_GREEN_GPIO_PIN * 2), (0x01 << LED_GREEN_GPIO_PIN * 2));
	REG_SET_VALUE((GPIOF_OTYPER), (0x01 << LED_GREEN_GPIO_PIN), (0x00 << LED_GREEN_GPIO_PIN));
	REG_SET_VALUE((GPIOF_OSPEEDR), (0x03 << LED_GREEN_GPIO_PIN * 2), (0x03 << LED_GREEN_GPIO_PIN * 2));
	REG_SET_VALUE((GPIOF_PUPDR), (0x03 << LED_GREEN_GPIO_PIN * 2), (0x00 << LED_GREEN_GPIO_PIN * 2));
	REG_SET(GPIOF_BSSR, (0x01 << (LED_GREEN_GPIO_PIN)));
	
	// 配置PF8
	REG_SET_VALUE((GPIOF_MODER), (0x03 << LED_BLUE_GPIO_PIN * 2), (0x01 << LED_BLUE_GPIO_PIN * 2));
	REG_SET_VALUE((GPIOF_OTYPER), (0x01 << LED_BLUE_GPIO_PIN), (0x00 << LED_BLUE_GPIO_PIN));
	REG_SET_VALUE((GPIOF_OSPEEDR), (0x03 << LED_BLUE_GPIO_PIN * 2), (0x03 << LED_BLUE_GPIO_PIN * 2));
	REG_SET_VALUE((GPIOF_PUPDR), (0x03 << LED_BLUE_GPIO_PIN * 2), (0x00 << LED_BLUE_GPIO_PIN * 2));
	REG_SET(GPIOF_BSSR, (0x01 << (LED_BLUE_GPIO_PIN)));
}

void toggle_led(uint32_t LED_COLOR_GPIO_PIN){
	if((REG32_VALUE(GPIOF_ODR) & (0x01 << LED_COLOR_GPIO_PIN)) == (0x01 << LED_COLOR_GPIO_PIN)){
		REG_SET(GPIOF_BSSR, (0x01 << (LED_COLOR_GPIO_PIN + 16)));
	}else{
		REG_SET(GPIOF_BSSR, (0x01 << LED_COLOR_GPIO_PIN));
	}
}
